configfile: "config/config.yaml"
ODATE=config['odate']

rule all:
    input:
        expand("mlops-pipeline-result/{ODATE}/load_lims.txt", ODATE=ODATE),
        expand("mlops-pipeline-result/{ODATE}/load_match_1.txt", ODATE=ODATE),
        expand("mlops-pipeline-result/{ODATE}/load_sample.txt", ODATE=ODATE)

rule load_lims:
    input:
        expand("mlops-pipeline-result/{ODATE}/export_lims.txt", ODATE=ODATE)
    output:
        expand("mlops-pipeline-result/{ODATE}/load_lims.txt", ODATE=ODATE)
    script:
        "scripts/load_lims.py"

rule export_lims:
    output:
        expand("mlops-pipeline-result/{ODATE}/export_lims.txt", ODATE=ODATE)
    script:
        "scripts/export_lims.py"

rule load_match_1:
    input:
        expand("mlops-pipeline-result/{ODATE}/sftp_odm.txt", ODATE=ODATE)
    output:
        expand("mlops-pipeline-result/{ODATE}/load_match_1.txt", ODATE=ODATE)
    script:
        "scripts/load_match_1.py"

rule sftp_odm:
    output:
        expand("mlops-pipeline-result/{ODATE}/sftp_odm.txt", ODATE=ODATE)
    script:
        "scripts/sftp_odm.py"

rule load_sample:
    input:
        expand("mlops-pipeline-result/{ODATE}/remain_sample.txt", ODATE=ODATE)
    output:
        expand("mlops-pipeline-result/{ODATE}/load_sample.txt", ODATE=ODATE)
    script:
        "scripts/load_sample.py"

rule export_sample:
    output:
        expand("mlops-pipeline-result/{ODATE}/remain_sample.txt", ODATE=ODATE)
    script:
        "scripts/remain_sample.py"