configfile: "config/config.yaml"
ODATE=config['odate']

rule all:
    input:
        expand("{ODATE}/load_lims.txt", ODATE=ODATE),
        expand("{ODATE}/load_match_1.txt"

rule load_lims:
    container: "docker://hub.docker.com/j2lab/minderadatatransfer:VD_Daily_0.2.1"
    input:
        expand("{ODATE}/export_lims.txt", ODATE=ODATE)
    output:
        expand("{ODATE}/load_lims.txt", ODATE=ODATE)
    shell:
        "/java/datatransfer.sh lims {ODATE}"

rule export_lims:
    container: "docker://hub.docker.com/j2lab/lambda-py:v1.0.14"
    output:
        expand("{ODATE}/export_lims.txt", ODATE=ODATE)
    shell:
        "python3 mlops-de-get-lims.py {ODATE}"

rule load_match_1:
    container: "docker://hub.docker.com/j2lab/minderadatatransfer:VD_Daily_0.2.1"
    input:
        expand("{ODATE}/sftp_odm.txt", ODATE=ODATE)
    output:
        expand("{ODATE}/load_match_1.txt", ODATE=ODATE)
    shell:
        "/java/datatransfer.sh odm {ODATE} odm1.3_fullMATCH_ODM_Export.xml MATCH-1"

rule sftp_odm:
    container: "docker://hub.docker.com/j2lab/lambda-py:v1.0.14"
    output:
        expand("{ODATE}/sftp_odm.txt", ODATE=ODATE)
    shell:
        "python3 mlops-de-get-odm.py {ODATE}"